languageCode: zh
defaultContentLanguage: zh
title: Developer Cheatsheet

googleAnalytics: G-J3NCP3DPFH

disableKinds:
- taxonomy

# Code higlighting settings
pygmentsCodefences: true
pygmentsCodeFencesGuesSsyntax: false
pygmentsOptions: ""
pygmentsStyle: "monokai"
pygmentsUseClasses: false

markup:
  goldmark:
    parser:
      autoHeadingIDType: "github-ascii"
    renderer:
      unsafe: true

module: 
  imports:
  - path: github.com/bep/docuapi/v2

params:
  search: true
  maxMenuDepth: 3 
  language_tabs:
  - key: shell
    name: Shell

languages:
  en:
    languageName: English
    weight: 1
    params:
      toc_footers:
        - <a href='https://github.dev/web3yoda/developer-cheatsheet' target="_blank">Edit on Github</a>
        - Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)
        - Hugo Theme by [bep](https://github.com/bep)
  zh:
    languageName: 简体中文
    weight: 2
    params:
      toc_footers:
        - <a href='https://github.dev/web3yoda/developer-cheatsheet' target="_blank">Edit on Github</a>
        - Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)
        - Hugo Theme by [bep](https://github.com/bep)
